SELECT * FROM customer LIMIT 10;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,SUM(purchase_amount_usd) as revenue
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,purchase_amount_usd
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount_usd >= (SELECT AVG(purchase_amount_usd)
                                                          FROM customer) ;
                                                          
-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,ROUND(AVG(review_rating),2) as average_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_review_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type,ROUND(AVG(purchase_amount_usd),2) as avg_purchase_amount
FROM customer 
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount_usd),2) AS avg_spend,
       ROUND(SUM(purchase_amount_usd),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

-- Q6. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH customer_type AS (
SELECT customer_id,previous_purchases,
CASE
 WHEN previous_purchases = 1 THEN 'New'
 WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
 ELSE 'Royal'
 END AS customer_segment
FROM customer
)
SELECT customer_segment,COUNT(*) as no_of_customers 
FROM customer_type
GROUP BY customer_segment;

-- Q7. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
SELECT category,item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category,item_purchased
)
SELECT item_rank,category,item_purchased,total_orders
FROM item_counts 
WHERE item_rank<=3;

-- Q8. What is the revenue contribution of each age group?
SELECT age_group,sum(purchase_amount_usd) as total_revenue 
FROM customer 
GROUP BY age_group
ORDER BY total_revenue DESC;






